# Generated by Django 4.1.1 on 2022-09-09 01:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.FloatField(verbose_name='Precio Unitario')),
                ('date_sold', models.DateTimeField(help_text='Fecha y hora a la que se registró la transacción', verbose_name='Fecha y hora')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product', verbose_name='Producto'),
        ),
    ]
