# Generated by Django 4.1.1 on 2022-10-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_batchsale_sale_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchsale",
            name="sale_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_sales",
                to="api.salehistory",
            ),
        ),
    ]
