# Generated by Django 4.1.1 on 2022-09-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_saleshistory_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleshistory',
            name='date_sold',
            field=models.DateField(auto_created=True, help_text='Fecha y hora a la que se registró la transacción', verbose_name='Fecha y hora'),
        ),
    ]
