# Generated by Django 4.1.1 on 2022-09-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='date_sold',
            field=models.DateField(auto_created=True, auto_now=True, help_text='Fecha y hora a la que se registró la transacción', verbose_name='Fecha y hora'),
        ),
    ]
